# Generated by Django 5.0.3 on 2024-03-28 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealerapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealer',
            name='mobileno',
        ),
    ]
